apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mnist-api
  template:
    metadata:
      labels:
        app: mnist-api
    spec:
      containers:
      - name: mnist-api
        image: 231599/mnist-ml:latest
        ports:
        - containerPort: 5000
